[viewer]
Title = "Go语言博客"
Description = "Go语言博客"
Logo = "/resource/images/logo.png"
Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
Github = "https://github.com/qiZach"
Bilibili = "https://space.bilibili.com/4204570/favlist?fid=1194087170"
Avatar = "http://n.sinaimg.cn/front/530/w700h630/20181209/9X84-hprknvt9518232.jpg"
UserName = "张思祺"
UserDesc = "长得非常帅的程序员"
[system]
CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
QiniuAccessKey = "替换自己的"
QiniuSecretKey = "替换自己的"
Valine = true
ValineAppid = "替换自己的"
ValineAppkey = "替换自己的"
ValineServerURL = "替换自己的"