[server]
Ip = "127.0.0.1"
Port = "8080"
[viewer]
Title = "Go语言博客"
Description = "Go语言博客"
Logo = "/resource/images/logo.png"
Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
Github = "https://github.com/qiZach"
Bilibili = "https://space.bilibili.com/4204570/favlist?fid=1194087170"
Avatar = "http://n.sinaimg.cn/front/530/w700h630/20181209/9X84-hprknvt9518232.jpg"
UserName = "张思祺"
UserDesc = "长得非常帅的程序员"
[system]
CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
QiniuAccessKey = "djvW_fT8yHsGK-b2veFvh7AvHTpzabjt2lMAX4Nv"
QiniuSecretKey = "6-fs9KCa7vY8NqLsX6qjpxOP7kJDi5k5txG2DqQh"
Valine = true
ValineAppid = "98w2gUA8Sxtv9Hwxin6zCJ5q-gzGzoHsz"
ValineAppkey = "8bgWZU6VkXqsNMKnvCSQBchx"
ValineServerURL = "https://98w2gua8.lc-cn-n1-shared.com"